services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      NEO4J_AUTH: ${NEO4J_USERNAME}/${NEO4J_PASSWORD}
      NEO4J_dbms_memory_heap_max__size: 2G
    ports:
      - "${NEO4J_DB_PORT}:7474"
      - "${NEO4J_APP_PORT}:7687"
    volumes:
      - ${NEO4J_VOLUME}:/data

  rabbitmq:
    image: rabbitmq:3.11-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-guest}
    ports:
      - "${RABBIT_QUEUE_PORT}:5672"
      - "${RABBIT_APP_PORT}:15672"
    volumes:
      - ${RABBITMQ_VOLUME}:/var/lib/rabbitmq

  nexarag.api:
    image: nexarag.api:latest
    build: 
      context: ./backend/src
      dockerfile: api/Dockerfile
    container_name: nexarag.api
    ports:
      - 8000:8000
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_DATABASE: neo4j
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
    depends_on:
      - neo4j
      - rabbitmq
    volumes:
      - ${NEO4J_VOLUME}:/data
      - ${DOCS_VOLUME}:/docs

  nexarag.frontend:
    image: nexarag.frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexarag.frontend
    ports:
      - ${API_PORT}:80
    depends_on:
      - nexarag.api

  nexarag.kg:
    image: nexarag.kg:latest
    build: 
      context: ./backend/src
      dockerfile: kg/Dockerfile
    container_name: nexarag.kg
    environment:
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
      NEO4J_DATABASE: neo4j
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
    depends_on:
      - neo4j
      - rabbitmq
    volumes:
      - ${NEO4J_VOLUME}:/data
