services:
  nexarag.neo4j:
    image: neo4j:latest
    container_name: nexarag.neo4j
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_use__neo4j__config=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.meta.data
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "password", "MATCH (n) RETURN COUNT(n);"]
      interval: 10s
      timeout: 5s
      retries: 5

  nexarag.rabbitmq:
    image: rabbitmq:3.11-management
    container_name: nexarag.rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  nexarag.api:
    image: nexarag.api:latest
    build:
      context: ./backend/src
      dockerfile: api/Dockerfile
    container_name: nexarag.api
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      NEO4J_URI: bolt://nexarag.neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
      NEO4J_DATABASE: neo4j
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      OLLAMA_BASE_URL: http://host.docker.internal:11434    
    depends_on:
      nexarag.neo4j:
        condition: service_healthy
      nexarag.rabbitmq:
        condition: service_healthy
    volumes:
      - docs_data:/docs

  nexarag.frontend:
    image: nexarag.frontend:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nexarag.frontend
    restart: unless-stopped
    ports:
      - ${API_PORT}:80
    depends_on:
      - nexarag.api

  nexarag.db:
    image: nexarag.db:latest
    build:
      context: ./backend/src
      dockerfile: db/Dockerfile
    container_name: nexarag.db
    restart: unless-stopped
    environment:
      NEO4J_URI: bolt://nexarag.neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
      NEO4J_DATABASE: neo4j
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
    depends_on:
      nexarag.neo4j:
        condition: service_healthy
      nexarag.rabbitmq:
        condition: service_healthy

  nexarag.kg:
    image: nexarag.kg:latest
    build:
      context: ./backend/src
      dockerfile: kg/Dockerfile
    container_name: nexarag.kg
    restart: unless-stopped
    environment:
      NEO4J_URI: bolt://nexarag.neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
      NEO4J_DATABASE: neo4j
      RABBITMQ_PASSWORD: guest
      RABBITMQ_USERNAME: guest
      OLLAMA_BASE_URL: http://host.docker.internal:11434
    volumes:
      - docs_data:/docs
    depends_on:
      nexarag.neo4j:
        condition: service_healthy
      nexarag.rabbitmq:
        condition: service_healthy

volumes:
  neo4j_data:
  rabbit_data:
  ollama_data:
  docs_data:
